---
title: "ASR_simmap"
output: html_document
date: "2022-12-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(phytools)
library(stringr)
library(ggplot2)
library(ape)

#proof of concept: ASR on a smaller cyanobacterial tree
treeOriginal <-read.tree(file ="SP.treefile", text = NULL, tree.names = NULL, skip = 0, comment.char = "",keep.multi = FALSE)

#prune out two outliers
treePrac <-drop.tip(treeOriginal,c("Acaryochloris.sp.MBIC11017","Acaryochloris.sp.CCMEE5410"))

#load location data
locationListPrac = read.csv("Habitats_Trimmed.csv",row.names=1,colClasses=c('factor','factor','factor','factor'))
rownames(locationListPrac) <- sapply(rownames(locationListPrac), function(x) { gsub("[\r\n]", "", x) })
fPrac<-setNames(locationListPrac$Habitat,rownames(locationListPrac))

#model testing
fitP.ER<-fitMk(treePrac,fPrac,model="ER")
fitP.ARD<-fitMk(treePrac,fPrac,model="ARD")
fitP.SYM<-fitMk(treePrac,fPrac,model="SYM")
AIC(fitP.ER,fitP.ARD,fitP.SYM)
plot.fitMk(fitP.ER) 
plot.fitMk(fitP.ARD)
plot.fitMk(fitP.SYM)

#mapping using three models
simTreePrac <- make.simmap(treePrac, fPrac, model="ER", nsim=100)
simTreePrac2 <- make.simmap(treePrac, fPrac, model="ARD", nsim=100)
simTreePrac3 <- make.simmap(treePrac, fPrac, model="SYM", nsim=100)
summary(simTreePrac)
summary(simTreePrac2)
summary(simTreePrac3)

#plots of posterior probabilities of ancestral states
tiff(filename="CB1219_ER_sim100_v2.tiff", width=1700, height=2000, res=300)
cols<-setNames(c("#bca0dc","#ccffcc","#c1f2fe","#008fb3","#EAD2A8"),levels(fPrac))
plot(summary(simTreePrac),colors=cols,fsize = 0.3, lwd = 1)
nodelabels(text=1,node=Ntip(treePrac)+1,frame="none",adj=c(2,0.5),col = "red")
legend("bottomright",c("Brackish","Fresh","Intertidal","Marine","Terrestrial"),pch=21,pt.bg=cols,pt.cex=2)
dev.off()

tiff(filename="CB1219_ARD_sim100_v2.tiff", width=1700, height=2000, res=300)
cols<-setNames(c("#bca0dc","#ccffcc","#c1f2fe","#008fb3","#EAD2A8"),levels(fPrac))
plot(summary(simTreePrac2),colors=cols,fsize = 0.3, lwd = 1)
nodelabels(text=1,node=Ntip(treePrac)+1,frame="none",adj=c(2,0.5),col = "red")
legend("bottomright",c("Brackish","Fresh","Intertidal","Marine","Terrestrial"),pch=21,pt.bg=cols,pt.cex=2)
dev.off()

tiff(filename="CB1219_SYM_sim100_v2.tiff", width=1700, height=2000, res=300)
cols<-setNames(c("#bca0dc","#ccffcc","#c1f2fe","#008fb3","#EAD2A8"),levels(fPrac))
plot(summary(simTreePrac3),colors=cols,fsize = 0.3, lwd = 1,spread.labels=TRUE,spread.cost=c(1,0))
nodelabels(text=1,node=Ntip(treePrac)+1,frame="none",adj=c(2,0.5),col = "red")
legend("bottomright",c("Brackish","Fresh","Intertidal","Marine","Terrestrial"),pch=21,pt.bg=cols,pt.cex=2)
dev.off()

#plots of stochastic matrices
tiff(filename="CB1219_ER_Qm_v2.tiff", width=1000, height=1000, res=105)
plot.fitMk(fitP.ER) 
dev.off()

tiff(filename="CB1219_ARD_Qm_v2.tiff", width=1000, height=1000,res=105)
plot.fitMk(fitP.ARD,fsize = 0.01) 
dev.off()

tiff(filename="CB1219_SYM_Qm_v2.tiff", width=1000, height=1000, res=105)
plot.fitMk(fitP.SYM) 
dev.off()
```

```{r}
#ASR on tree of life
tree2 <-read.tree(file ="RAxML_ToL_Final.tree", text = NULL, tree.names = NULL, skip = 0, comment.char = "", keep.multi = FALSE)
locationList = read.csv("finalInput_1218.csv",row.names = 1, colClasses=c('character', 'factor'))
rownames(locationList) <- sapply(rownames(locationList), function(x) { gsub("[\r\n]", "", x) })
f<-setNames(locationList$location,rownames(locationList))

simTree <- make.simmap(tree2, f, model="SYM", nsim=1)
simTree2 <- make.simmap(tree2, f, model="ARD", nsim=100)
simTree3 <- make.simmap(tree2, f, model="SYM", nsim=100)
simTree4 <- make.simmap(tree2, f, model="ER", nsim=300)

fit.ER<-fitMk(tree2,f,model="ER")
fit.ARD<-fitMk(tree2,f,model="ARD")
fit.SYM<-fitMk(tree2,f,model="SYM")
AIC(fit.ER,fit.ARD,fit.SYM)

tiff(filename="test1218_2.tiff", width=2000, height=2000, res=50)
c<-setNames(c("black","#008fb3","#c1f2fe","#EAD2A8","white"),levels(f))
plot(summary(simTree2),colors=c,fdsize = 0.05, lwd = 1,show.tip.label = FALSE)
legend("bottomright",c("hostAssociated","marine_deep","marine_shallow","terrestrial","Ungrouped"),pch=21,pt.bg=c,pt.cex=2)
dev.off()
```


