---
title: "Tara Ocean metagenome COG and nutrient limitations"
author: "Jimmy Zhong"
date: "4/12/2023"
output: html_document
---

## Jimmy's ibaray set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# setting the working directory to the location of this file
setwd(dirname(rstudioapi::getActiveDocumentContext()$path ))
source(".init_tara.R")

tara_md = init_tara_metadata()
COGabun = get_COGabundance() # only the prokaryote fraction

tara_md = tara_md[colnames(COGabun), ]

joanne_gene = c("COG0226", "COG0573", "COG0581", "COG4985", "COG1117", "COG3638", "COG3221", "COG3639", "COG3624", "COG3625", "COG3626", "COG3627", "COG4107", "COG4778", "COG3454", "COG3709", "COG2764", "COG0395", "COG1653", "COG1134", "COG1392", "COG1840", "COG0704")

joanne_table = COGabun[joanne_gene, ]
```

# printing the raw data
```{r}
tmp = COGabun[joanne_gene, ]
tmp$COG_function = c("PstS", "PstC", "PstA", "PstA_auxiliary", "PstB", "PhnC", "PhnD", "PhnE", "PhnG", "PhnH", "PhnI", "PhnJ", "PhnK", "PhnL", "PhnM", "PhnN", "PhnB", "UgpE", "UgpB", "TagH", "YkaA", "AfuA", "PhoU")
tmp = tmp[c(ncol(tmp), 2:ncol(tmp)-1)]
write.csv(tmp, "phosphorous_COGs_abundance.csv", row.names=TRUE)
```

# doing raw correlations
```{r}
joanne_cor_spear = as.data.frame(t(mapply(return_corr2, as.data.frame(t(joanne_table)), "log_PO4")))
colnames(joanne_cor_spear) = c("spearman p-value", "spearman correlation")

joanne_cor_pearson = as.data.frame(t(mapply(return_corr2, as.data.frame(t(joanne_table)), "log_PO4", "pearson")))
colnames(joanne_cor_pearson) = c("pearson p-value", "pearson correlation")

joanne_cor = cbind(joanne_cor_spear, joanne_cor_pearson) %>%
  arrange(abs(`spearman p-value`))

write.csv(joanne_cor, "phosphorous_correlations.csv", row.names=TRUE)
```

# run MaAsLin2
```{r}
# result_dir = 'MaAsLin_out/joanne_logPO4_Oxygen_temp_logDepth_size'
# param = c('size_fraction','Mean_Temperature', "log_depth", 'Mean_Oxygen', 'log_PO4') # 19 sig with PO4, 9 sig with depth

result_dir = 'MaAsLin_out/joanne_logPO4_temp_logDepth_size'
param = c('size_fraction','Mean_Temperature', "log_depth", 'log_PO4') # 19 sig with PO4, 10 sig with depth

result_dir = 'MaAsLin_out/joanne_iron_logPO4_logNO2NO3_Salinity_Oxygen_temp_logDepth_size_long_lat'
param = c('size_fraction','Mean_Temperature', "log_depth", 'Mean_Salinity',
           'Mean_Oxygen', 'log_PO4','log_NO2NO3', "sqrt_iron")

fit_data <- Maaslin2(
    joanne_table, tara_md, result_dir, transform = "LOG",
    fixed_effects = param,
    random_effects = c("Mean_Lat", "Mean_Long"),
    reference = 'size_fraction,0.22-1.6',
    max_significance = 0.05,
    normalization = 'NONE',
    min_prevalence = 0.33, # at least 1/3 of the sample has it
    standardize = FALSE)
```

